name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}  # important! login shell to correctly use conda

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda & Python 3.12
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge, defaults
          channel-priority: strict
          miniforge-variant: Miniforge3
          python-version: '3.12'
          auto-update-conda: false
          use-mamba: false

      - name: Install namaster with conda
        run: |
          conda install -y -c conda-forge namaster

      - name: Install your package and dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Run tests
        run: |
          cd tests
          pytest -s .

